### ISSUE TITLE
demo collection with phone

### ISSUE THREAD

**Issue by YeeCY** [StanfordVL/robosuite#101]
I notice that there are interfaces to control the simulated robot with a phone, like https://sites.google.com/stanford.edu/iris/ and https://roboturk.stanford.edu/. But I cannot find it in this repo, is there a plan to open source it?

**Comment by amandlek** [comment]
There are no current plans to open source the phone interface - it is still under active development. You can still collect demonstrations using the keyboard or spacemouse interfaces thought.
