### ISSUE TITLE
Compatibility with Python3.6

### ISSUE THREAD

**Issue by ImranRolo** [StanfordVL/robosuite#13]
Are there any plans to make robosuite compatible with Python3.6. Tensorflow doesn't offer support for Python3.7 and I want to use both together.

**Comment by yukezhu** [comment]
robosuite is compatible with Python 3.6. Although we provide official support to 3.5 and 3.7, there's nothing really preventing it from running with 3.6. Please let us know if you encounter any issue running robosuite on 3.6.
