### ISSUE TITLE
Action data of human demo

### ISSUE THREAD

**Issue by isk03276** [StanfordVL/robosuite#16]
Hi, 

I'm generating demo data through the "collect_human_demonstrations" script file. I have a question related to this.

Can I get data corresponding to robot action in demo? (it may be torque of robot joint)

**Comment by amandlek** [comment]
Yes you can. Check out this line [here](https://github.com/StanfordVL/robosuite/blob/master/robosuite/scripts/collect_human_demonstrations.py#L170). We store the joint velocities and commanded gripper actuations per trajectory in the hdf5 demo file. You can read these and concatenate them to recover the robot actions.
