### ISSUE TITLE
what is "states(dataset) - flattened mujoco states"?

### ISSUE THREAD

**Issue by isk03276** [StanfordVL/robosuite#24]
Hi, I am wondering what the "flattened mujoco states" is in the structure of demonstrations.
Can you tell what kind of data is contained in "states"?

Thanks!

![image](https://user-images.githubusercontent.com/23740495/54574236-eefeb180-4a32-11e9-9fd7-241fbc5abbc4.png)

**Comment by amandlek** [comment]
This is the low-level mujoco state, which is the minimal information needed to reconstruct the state of the simulator. This can be used to playback the demonstrations, as shown [here](https://github.com/StanfordVL/robosuite/blob/master/robosuite/scripts/playback_demonstrations_from_hdf5.py#L100), frame by frame.

**Comment by Gaoee** [comment]
Is there any document introduces what kind of states are contained in "states"? Because I want to use the positions of objects in the demonstrations data.

**Comment by amandlek** [comment]
Take a look at [this](https://github.com/StanfordVL/robosuite/blob/master/robosuite/scripts/playback_demonstrations_from_hdf5.py#L80). You can just set the state of the environment, then retrieve whatever quantities you would like from the simulator itself (or by calling `env._get_observation()`)

**Comment by Gaoee** [comment]
OK, thank you. So, if I want to get more observations which are not contained in demonstrations, I need to playback the demonstrations and retrieve from the environment.
