### ISSUE TITLE
Support for mujoco 2.0

### ISSUE THREAD

**Issue by hartikainen** [StanfordVL/robosuite#26]
It would be nice if robosuite officially supported mujoco 2.0. I've ran most of the existing environments with mujoco 2.0 and they seem to run fine. I think it's possible that the upgrade is just a matter of bumping up the mujoco version in the requirements.txt and setup.py and no changes in the robosuite code base are needed.

I'd be happy to submit a PR for this.

**Comment by nav74neet** [comment]
Yes I totally agree with @hartikainen, it would be great to upgrade to mujoco 2.0
