### ISSUE TITLE
How can I move the objects as I wish in this environment?

### ISSUE THREAD

**Issue by kaixindelele** [StanfordVL/robosuite#29]
Hi, thank you for providing a complete simulation robotic arm a lot. 
However, now I want to get more different pictures about the state, I don't know how to move the objects?(e.g. bottles, mikes.)
I tried to modify the location  of the random initialization, but the change was not obvious.
Perhaps, this project is too big to review all details especially my English is not skilled~ 
May I could not find your example programs?
Can you please provide one direction and let me go to learn how to move those, your project or mujoco-py?

**Comment by amandlek** [comment]
You can see this comment [here](https://github.com/StanfordVL/robosuite/blob/master/robosuite/models/tasks/placement_sampler.py#L52), which explains that the range of the uniform random initializer is specific to the center of the table. So one way to control object placement is just to write your own placement initializer. Basically, every environment owns a task which specifies the model (for example, https://github.com/StanfordVL/robosuite/blob/master/robosuite/environments/sawyer_lift.py#L163), and the task uses the initializer to place objects (for example, [here](https://github.com/StanfordVL/robosuite/blob/master/robosuite/models/tasks/table_top_task.py#L65)).
