### ISSUE TITLE
Robot appears differently in window rendering vs offscreen rendering from camera

### ISSUE THREAD

**Issue by yuchen93** [StanfordVL/robosuite#30]
Hi, 

I am trying to generate camera observations of rollouts of a policy trained with Surreal. 
However I found that the Sawyer robot rendered with env.unwrapped.render() onscreen and the observation rendered with env.unwrapped.sim.render() look different. More specifically, the one rendered in the simulation window has more details whereas the one rendered in offscreen mode does not resemble the real look of the robot:

![image](https://user-images.githubusercontent.com/14132226/57806963-d9052880-7725-11e9-9909-dc5321ee06dd.png)

Is there a way to obtain the more realist looking robot in observation images? 

Thanks

**Comment by amandlek** [comment]
I suspect there is something going on with one of the wrappers you are using for training with Surreal. The collision mesh is being rendered currently. You can change this by making sure this parameter is False - see [this](https://github.com/StanfordVL/robosuite/blob/master/robosuite/environments/sawyer.py#L21).
