### ISSUE TITLE
Itergrating robosuite with different robots

### ISSUE THREAD

**Issue by isk03276** [StanfordVL/robosuite#38]
Hi,
I want to integrate robosuite with Kinova's Jaco2 (j2n6s300) robot arm model.
Are there tutorials or guidelines for this?
Thank you.

**Comment by yukezhu** [comment]
Hi @isk03276 we are open to incorporate new robot arm models in robosuite. However, Jaco2 has not been a priority on our side. We are currently focusing on robots that are used in our research. We've just added support to the Panda arm (see PR https://github.com/StanfordVL/robosuite/pull/46). This PR will give you an idea how to add new robot models of your interest. If you would like to contribute to this repo with new robot models, please submit a PR. Thanks!
