### ISSUE TITLE
Renderer real-time compensation is out of sink

### ISSUE THREAD

**Issue by eugval** [StanfordVL/robosuite#39]
Hello,

I noticed that the render behaves sometimes strangely, with regards to the frequency of rendering and timing.

It is possible to see this by slightly changing the ```demo.py``` file by adding  ```sleep```and ```print``` calls : 
![image](https://user-images.githubusercontent.com/24697174/62281754-3fa50300-b446-11e9-9b6a-ef09bb6ddcd4.png)

Launching the demo then with say Sawyer lift we can see that it only renders every so often, not at every call of ```render()``` . Moreover, if we set up a test at a control frequency of 5 hz, and allow for 20 timesteps, we can see that it does not render in 4s which is what would have been expected in real-time.

Upon further investigation, this comes from mujoco-py, that implements a compensation to make the rendering real-time (c.f. lines 194-204 in mjviewer.py):
![image](https://user-images.githubusercontent.com/24697174/62282129-ec7f8000-b446-11e9-8b8c-f5446d1a9633.png)

Now, this compensation relies on ```sim.nbsubsteps``` which tells ```mujoco-py``` how many simulation steps to take for every control step. This here is set to 1, but the functionality is re-implemented in ```base.py```  (note that step in base.py reasons in terms of frequencies and time while ```sim.nbsubsteps``` just considers the number of simulation substeps):
![image](https://user-images.githubusercontent.com/24697174/62282336-44b68200-b447-11e9-8374-af0f91f62627.png)

The result of this is that every-time that ```render()``` is called, mujoco-py compensates time as if only one simulation step was taken between consecutive render calls  (as sim.nbsubsteps =1), while there are actually more taken, depending on the ```control_freq``` ; which makes the whole thing go out of sink.

I made a quick and dirty hack to compensate for this, but a better ideas are more than welcome:
In ```base.py```:
1. I added ```self.viewer._render_every_frame``` = True in ```_reset_internal``` to stop the compensation by ```mujoco-py```
2. At every render call I added ``` time.sleep(1/self.control_freq)``` to get back to real-time.

This **does not** take into account the actual compute time  (as opposed to ```mujoco-py``` which does) between render calls so it is actually not showing real-time, but its an approximate fix if you don't care about being very exact.

![image](https://user-images.githubusercontent.com/24697174/62283022-8bf14280-b448-11e9-9006-565c12e130eb.png)

![image](https://user-images.githubusercontent.com/24697174/62283044-99a6c800-b448-11e9-88a5-88d986c86cef.png)

Thanks!!

**Comment by cremebrule** [comment]
We've fixed this in the upcoming release!
