### ISSUE TITLE
Is it possible to manipulate softbody with robosuite?

### ISSUE THREAD

**Issue by imankgoyal** [StanfordVL/robosuite#41]
Hi, 
I find the robosuite framework very cool. Does it support manipulating soft objects like cloth, ropes? As far as I understand, mujoco does support soft object manipulation. Does that support come out-of-the-box for robosuite? If not then any ideas on how to do it?
Thanks!

**Comment by amandlek** [comment]
MuJoCo 2.0 has some support for this, and newer versions of mujoco-py support MuJoCo 2.0, but we don't have out-of-the-box support for this yet in terms of environments. It shouldn't be too hard to design your own environment that uses MuJoCo 2.0 though.
