### ISSUE TITLE
Memory leak of the IK controller?

### ISSUE THREAD

**Issue by eugval** [StanfordVL/robosuite#42]
Hello!

I would like to use the ``ik_wrapper`` and the ``sawyer_ik_controller`` in order to control the robot in end-effector pose, but I am noticing that my environment consumes more and more memory over time!

Because I want to use distributed environments in order to  speed up learning,  my program ends up running out of memory.

I am wandering if this could be a memory leak somewhere in the controller? The only thing that I could think of is pybullet (looking at the code, i don't see where else this could be coming from).

Any Ideas? Perhaps any recommendation on what other packages I could use to replace pybullet do the the inverse kynematics?

Many Thanks,
Eugene

**Comment by amandlek** [comment]
[Here's](https://github.com/StanfordVL/bullet3_ik) a fix that you can use - you'll need to compile it from source.

**Comment by eugval** [comment]
Great! Thank you, that worked!!
