### ISSUE TITLE
Share source code for Real Sawyer Robot interface 

### ISSUE THREAD

**Issue by thanhkaist** [StanfordVL/robosuite#43]
Robosuite is an amazing open-source code that helps the researchers a lot to benchmark their algorithms. I really appreciate your effort and kindness to share this source code. Could you share the real robot API interface to work with the real Sawyer robot? That would also help people a lot to see algorithm work on the real robot. Currently, I am working on real Sawyer robot. I really look forward to seeing your sharing.

Thank you

**Comment by yukezhu** [comment]
Hi, we have recently released our framework that unifies BulletPhysics simulation and real Saywer interface. Please feel free to check it out.

https://github.com/Stanfordvl/robovat
