### ISSUE TITLE
From actual sawyer urdf to updated mujoco XML files?

### ISSUE THREAD

**Issue by eugval** [StanfordVL/robosuite#44]
Hello,

Please correct me if I am wrong, but I have noticed that your mujoco XML files have been constructed using the ``standard'' urdf description of the sawyer provided by rethink [here](https://github.com/RethinkRobotics/sawyer_robot).

Do you by any chance have functionality that could take the urdf obtained from the parameter server of the actual physical sawyer and update the mujoco xml files accordingly? (Did you have to write all the xml files by hand or do you have any scripts that helped you obtain them from the urdf description?)

Thanks!

**Comment by amandlek** [comment]
We used a binary provided by mujoco - if you go to your mujoco installation (for example, `~/.mujoco/mjpro150/bin`) there is a `compile` binary that you can use to convert from urdf to mjcf. However, it is not perfect, and some more manual tuning might be required.
