### ISSUE TITLE
docs/demonstrations.md: Incorrect Path to Linked Documents

### ISSUE THREAD

**Issue by RexxarCHL** [StanfordVL/robosuite#5]
Links to playback_demonstrations_from_hdf5 and collect_human_demonstrations have incorrect relative paths to actual documents.

Current link:
https://github.com/StanfordVL/robosuite/blob/master/docs/robosuite/scripts/collect_human_demonstrations.py
Actual link:
https://github.com/StanfordVL/robosuite/blob/master/robosuite/scripts/collect_human_demonstrations.py

**Comment by amandlek** [comment]
Thank you for pointing this out! Should be fixed now.
