### ISSUE TITLE
Increasing Simulation speed

### ISSUE THREAD

**Issue by febert** [StanfordVL/robosuite#51]
Hi, 

simulation speed with standard parameters is currently very slow.
For a single env.step() it takes about 0.15 seconds.

Is there a parameter that allows speeding this up? I know there are Mujoco solver parameters like the number of iterations it takes at every step. Is that exposed in robosuite anywhere?

Thanks!

**Comment by amandlek** [comment]
It certainly shouldn't take that long - what parameters and settings are you using? Do you have a script that can reproduce the problem? If this is with image observations, this could be a rendering speed issue related to making sure that the correct version of `mujoco-py` is installed (the one that actually leverages the GPU).
