### ISSUE TITLE
Problem playing back demonstrations using inverse kinematics

### ISSUE THREAD

**Issue by febert** [StanfordVL/robosuite#52]
Hi, 

I'm trying to play back demonstrations using inverse kinematics using this script:
https://github.com/kpertsch/robosuite/blob/dev_frederik/robosuite/scripts/replay_dataset.py#L60

Using the "bins-Bread" data it produces motions that look random and do not pick up anything.

Could this be an issue with the control_freq parameter? Was this data collected with control_freq=100?

Thanks at lot!

**Comment by amandlek** [comment]
Is this using RoboTurk data, or data that you collected yourself? The RoboTurk dataset doesn't support open-loop deterministic action playback unfortunately (the fix for this wasn't implemented in Robosuite until after collecting the data).

**Comment by febert** [comment]
I was trying to use Roboturk data. What was the fix to it?

**Comment by amandlek** [comment]
https://github.com/StanfordVL/robosuite/blob/master/robosuite/scripts/collect_human_demonstrations.py#L70
