### ISSUE TITLE
[BUG] Off-screen render images are incorrectly mirrored

### ISSUE THREAD

**Issue by SudeepDasari** [StanfordVL/robosuite#56]
I've found that images rendered off-screen by mujoco_py (w/ `sim.render`) are upside down and mirrored when compared to images rendered by the Mujoco viewer. While the former issue can be fixed by adjusting the camera transform, the later issue can only be fixed by flipping the image buffers in code.

For example, below is the default image returned by the `sawyer_pick_place` environment, a rotated version of it for convenience, and the image shown by the Mujoco Viewer. Note that the bin is mirrored between the rotated and "real" images. 

I believe the Mujoco viewer's rendering is correct, as the right baxter gripper appears on the **robot's left** in the sim rendering. To fix this issue I flipped the image buffer's width channel in code, though there may be a better way to resolve this.

| From sim | Rotate 180 degrees | From viewer |
| --- | --- | --- |
| ![raw_sim](https://user-images.githubusercontent.com/16604347/73285836-a4a69f00-41c4-11ea-9144-be8231b6cf51.png) | ![rotated_sim](https://user-images.githubusercontent.com/16604347/73285841-a708f900-41c4-11ea-8606-aed02e032b02.png) | ![viewer_resize](https://user-images.githubusercontent.com/16604347/73286150-17177f00-41c5-11ea-80f2-2be0bc8e83e3.png)

**Comment by amandlek** [comment]
This is indeed true, and an issue with either mujoco-py or mujoco itself. For most use cases - I've been manually flipping the image axis myself, as you have done - since we rely on the `env.sim.render` call, which comes directly from mujoco-py.

**Comment by IcarusWizard** [comment]
Hey guys. I just encounter the same issue in the latest version. Is there any plan to fix the bug within this repo? Or do we have to do the flipping manually?

**Comment by amandlek** [comment]
You can just set [this option](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/macros.py#L28) appropriately to handle the flipping for you
