### ISSUE TITLE
Missing and Broken Documentation

### ISSUE THREAD

**Issue by ahundt** [StanfordVL/robosuite#7]
I read through all the documentation and a lot of details necessary to run and contribute to this project appear to be missing so I'd appreciate your help. Will the documentation be expanded at some point?

Examples of missing info for the robosuite:
1. The main [README.md](https://github.com/StanfordVL/robosuite) does not seem to contain a link to surreal itself.
2. Could the [quickstart](https://github.com/StanfordVL/robosuite/blob/master/README.md#quick-start) be updated to cover the steps from a fresh single machine to running a demo? The current quickstart assumes everything is already installed and working.
3. The [link to code in creating_environment.md is broken](https://github.com/StanfordVL/robosuite/blob/master/docs/creating_environment.md)
4. Some [examples seem to be in the scripts folder](https://github.com/StanfordVL/robosuite/tree/master/robosuite/scripts), could you add an overview of their purpose?
5. The scripts folder isn't mentioned in the main [readme.md](https://github.com/StanfordVL/robosuite/blob/master/README.md)
6. [existence of action_spec() and environment_spec()](https://github.com/SurrealAI/surreal/blob/master/docs/env.md) is in a separate repository. Specs are a dictionary, but what do those specs typically contain? Are there recommended strings?

Thanks for your help!

**Comment by amandlek** [comment]
@ahundt Thanks for pointing these documentation issues out! We've addressed some of them in the PRs that you see above.
