### ISSUE TITLE
RoboTurk dataset playback failed when using camera_name="agentview"

### ISSUE THREAD

**Issue by rhett-chen** [StanfordVL/robosuite#84]
I want playback RoboTurk dataset demonstration from states, but when i set the camera_name="agentview", I encountered the following error：
![image](https://user-images.githubusercontent.com/47732089/79691984-173f8c00-8295-11ea-951c-99f2acf738a0.png)
However, when i set the camera_name="tabletop", i encoutered the same error:
![image](https://user-images.githubusercontent.com/47732089/79692022-5c63be00-8295-11ea-95f1-ebffa1075248.png)
This made me confused， when i set camera_name="agentview", i was told no camera with name agentview and tabletop is available, but when i set camera_name="tabletop", i was told no camrea with name tabletop and agentview is available, which is contradictory. For "frontview", 'birdview" and "eye_in_hand", no error was reported. 
I wonder what i should do if i want to get the "agentview" images. Thanks.

**Comment by aprendizaje-de-maquinas** [comment]
Hi we have updated the dataset to include the "agentview" camera. Please download the dataset again. Let us know if you encounter any other issues with the dataset.
