### ISSUE TITLE
Policy frequency vs. Controller frequency

### ISSUE THREAD

**Issue by asadalishahid** [StanfordVL/robosuite#86]
Hi, 
Thanks for the great work. I am wondering why is the frequency of policy much lower than that of controller. 20Hz vs 500Hz. If the real controller can operate at 500Hz, wouldn't it be good to output actions from policy at same rate. 

It would be of great help to me in a project if I can clarify this issue. 
Thanks

**Comment by yukezhu** [comment]
You have the flexibility to choose to set the policy frequency to the same as controller frequency, but making the distinction between these two is a practical design. Some controllers use high-level action spaces that do not need to change decisions at 500Hz, and when using deep learning models, inference time might not be fast to run at 500Hz. These are the scenarios a lower frequency, e.g., 20Hz, is preferred.

**Comment by asadalishahid** [comment]
Thanks!
