### ISSUE TITLE
Robosuite v1.0 IK URDF file not found

### ISSUE THREAD

**Issue by jordanleex13** [StanfordVL/robosuite#89]
Ran into the following error when using v1 branch using IK controller. Run on Ubuntu 18.04

URDF file '/h/jordan/robosuite/robosuite/models/assets/bullet_data/Sawyer_description/urdf/Sawyer_arm.urdf' not found

Think you might need to use lowercase robot name due to your folder naming conventions
https://github.com/StanfordVL/robosuite/blob/v1.0/robosuite/controllers/ee_ik.py#L208

**Comment by cremebrule** [comment]
Thanks for the catch! Fixed
