### ISSUE TITLE
`cffi` package is required

### ISSUE THREAD

**Issue by fxia22** [StanfordVL/robosuite#91]
I tried fresh installations in both ubuntu and os x, looks like `cffi` is required to build `mujoco-py` but not included in dependencies.

```
    File "/private/var/folders/pk/x1lqwccj6_5gnd2rjpn5mddh0000gn/T/pip-build-5kn7uyp2/mujoco-py/mujoco_py/builder.py", line 16, in <module>
      from cffi import FFI
  ImportError: No module named 'cffi'
```

**Comment by amandlek** [comment]
it's a dependency of mujoco-py, so we expect it will be installed through there
